### ISSUE TITLE
May we have three colors?

### ISSUE THREAD

**Issue by 2klab** [tubededentifrice/streamdeck-crypto#1]
Would be great rather than having a single color for a value going out of a condition, to have a color for a value going out of a first condition (probably <min) and another one for a value going out of a second condition (probably >max).

'<= value : red
'>= value : white
'standard : blue

Thanks! Any suggestion appreciated.

**Comment by tubededentifrice** [comment]
`Alert` is just a boolean, it doesn't have a notion of `>=` or `<=`
However, I can investigate a "Color rule", that would returns a string, which would take precedence over default colors if set. Would that work for you?

**Comment by tubededentifrice** [comment]
Added in https://github.com/tubededentifrice/streamdeck-crypto/commit/eed06702f5a34c81a555629489c25fb2e100bb7a
Which adds a field to define the background color and another for the text color (JS snippets), so you can have an infinite number of different alerts :)

**Comment by tubededentifrice** [comment]
(I sent the new version to Elgato, hopefully it will be available soon as an update, meanwhile you can run it from source by following https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/ )

**Comment by 2klab** [comment]
Bonjour 

Merci beaucoup tubededentifrice !

Cordialement 
Jv

**Comment by 2klab** [comment]
Testing the solution:
Can we have:
Value>9666?’red’:value>9665?’green’:’blue’

Thanks

**Comment by tubededentifrice** [comment]
Yes, with parenthesis:
`value>9666?'red':(value>9665?'green':'blue')`

It pure JS, so you can also write it like:
`if (value>9666) { 'red'; } else if (value>9665) { 'green'; } 'blue';`

**Comment by 2klab** [comment]
Thank you so much!
Very useful.
