### ISSUE TITLE
Since new Update of StreamDeck only BlackIcons

### ISSUE THREAD

**Issue by Marv2190** [tubededentifrice/streamdeck-crypto#12]
Hello,
today a new Update of Streamdeck was rolled out. 
After that the Plugin dont work anymore :(
I can see the settings and drag it to the tiles but they keep beeing black.

**Comment by woodydeck** [comment]
I can second that behavior.

**Comment by tubededentifrice** [comment]
I had server issues back then, I believe that's what caused the black outage, sorry.
It broke essentially everything, including retrieval of the pairs, but I believe it should all be solved by now.
FYI I plan to make the plugin standalone again in the future.
