### ISSUE TITLE
Refresh timer

### ISSUE THREAD

**Issue by rAlexandre00** [tubededentifrice/streamdeck-crypto#14]
Could you add to the config a way to set the refresh timer? Right now I think it is little bit slow (if even refreshing).

**Comment by tubededentifrice** [comment]
According to https://github.com/tubededentifrice/streamdeck-crypto/blob/master/Sources/com.courcelle.cryptoticker.sdPlugin/js/ticker.js#L729 it should refresh every 5 minutes, is it not?
