### ISSUE TITLE
[Feature Request] More Coin Pairs

### ISSUE THREAD

**Issue by Marv2190** [tubededentifrice/streamdeck-crypto#15]
I saw https://github.com/tubededentifrice/streamdeck-crypto/issues/6 .
Couldnt you "just" add Coinmarketcap oder Coingecko api?
With that it should be possible to get access to all coins, shoudlnt it?

Greet Plugin anyway, works very well :) Thank you

**Comment by tubededentifrice** [comment]
Hello
Unfortunately it looks like those APIs are either paid/too restrictive in their free version, or doesn't provide the full set of functions necessary (no historical data).
