### ISSUE TITLE
It stopped working after updating to streamdeck6

### ISSUE THREAD

**Issue by ethereum113** [tubededentifrice/streamdeck-crypto#16]
It stopped working after updating to streamdeck6

**Comment by mrksnrm** [comment]
Same here, after last Stream Deck update all little crypto "screens" are blacked out

**Comment by tubededentifrice** [comment]
Sorry for the inconvenience, I'll fix it as soon as I can (within a week or so hopefully)

**Comment by tubededentifrice** [comment]
Hey there, can you confirm you're still experiencing the problem? I just upgraded to v6 and everything seems to work just fine.

**Comment by mrksnrm** [comment]
One of the most used app/function with my streamdeck works again, thanks a lot!

**Comment by ethereum113** [comment]
Resolved! I'd be happy to show more coins if I could get them from coingecko too!
