### ISSUE TITLE
Nice black buttons

### ISSUE THREAD

**Issue by tinkerspy** [tubededentifrice/streamdeck-crypto#20]
I got my Stream Deck XL this week and tried this plugin. It doesn't seem to work at all the buttons stay black.

**Comment by tubededentifrice** [comment]
Which provider/pair did you choose?
The defaults (Bitfinex / BTCUSD) seems to work just fine out of the box for me

**Comment by tinkerspy** [comment]
I tried them all.

![image](https://user-images.githubusercontent.com/13277092/227716227-2fd8715a-3a7d-4906-9dab-2be9c48ea6e3.png)

Button stays completely black.

![image](https://user-images.githubusercontent.com/13277092/227716240-54c372fd-327d-412f-a603-fef2f012dec6.png)

Anything I can check/debug?

**Comment by GarryMartin** [comment]
That same combination works fine for me on my XL. Perhaps it isn't a StreamDeck or plugin issue? Do you perhaps have a firewall, proxy or adblocker that is blocking the outgoing API calls for example? Can you disable them temporarily to test? Do other StreamDeck plugins that access the Internet work without issue?

**Comment by tinkerspy** [comment]
The only internet connected button I use is a speedtest and that works fine. Does stream deck or this plugin use one of my browsers? If so, which? I use Firefox/chrome/edge/brave... ;-) Turning of my main browser (FF) ad blocker (ublock) had no effect.

My Internet connection goes through a standard cable modem, no fancy firewalling. 
I turned off the win 11 firewall, no effect.

Still looking at:

![image](https://user-images.githubusercontent.com/13277092/227717971-e5890bee-b065-4a70-9eb1-76b61dec8710.png)

**Comment by tubededentifrice** [comment]
Could you pease remove the "title" (ie. where you put "btc") it's an annoyance -- It's mandatory to have it, can't be removed AFAIK, and breaks stuff (I'm not at my desk so haven't tried, but could be what's breaking your display)

Otherwise, could you enable the debugging mode (see https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging-your-javascript-plugin ) to see if it reports any error in the console?

Thanks.

**Comment by tinkerspy** [comment]
Done that (and removed the text;-))

![image](https://user-images.githubusercontent.com/13277092/227719799-f34926c2-c88f-44c0-a816-ad2af766e591.png)

**Comment by tubededentifrice** [comment]
Do a 
`curl -vvvv "https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.3/signalr.min.js"`

If you can't connect to Cloudflare CDN to download libraries, no way it would work indeed.
Also, can you access https://cloudflare.com ? Or Cloudflare protected websites, like https://tproxy.opendle.com/api/debug/ip ?
Do you have HTTPS decryption or proxy in place or something similar?
Anyway, the curl -vvvv should be able to tell what's really going on.

Thanks

**Comment by tinkerspy** [comment]
Strange indeed.

```
curl -vvvv "https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/5.0.3/signalr.min.js"
*   Trying 104.17.24.14:443...
* Connected to cdnjs.cloudflare.com (104.17.24.14) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to cdnjs.cloudflare.com:443
* Closing connection 0
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to cdnjs.cloudflare.com:443
```

Some kind of TLS problem apparently. The other URLs you mention work fine.
It's hard to imagine that would be unique to my Win 11 system...

Anyway, the other cryptotrackers work so, I have 'options'. ;-)

Thanks.

**Comment by tubededentifrice** [comment]
Looks like you've a problem with TLS.
Can you do the following:
`Right-click on Start and select Run. Type inetcpl.cpl into the run box and press Enter. On the Advanced tab of the Internet Properties dialogue, make sure at least TLS 1.2 and 1.3 are enabled.`

Thanks

**Comment by tubededentifrice** [comment]
(I tested on Windows 11 and I have no issue on my end; you might need a reboot after changing that setting)

**Comment by tinkerspy** [comment]
Thanks, but both are enabled (and the insecure versions disabled)

![image](https://user-images.githubusercontent.com/13277092/227795119-4fb0c531-8a16-447f-acb5-9fba3dd76ac3.png)

**Comment by 4lw4ys** [comment]
Just chiming in to say that I experience this issue on macOS 14.0 and am able to reach Cloudflare.

**Comment by tubededentifrice** [comment]
In the latest version I've embedded SignalR with the plugin, which should fix that problem
