### ISSUE TITLE
Prices not updating anymore and black screen sometimes

### ISSUE THREAD

**Issue by Adelyann** [tubededentifrice/streamdeck-crypto#21]
Hello,

Since the update to StreamDeck 6, prices doesn't seem to update anymore. It gets the price at startup of stream deck and then doesn't update (Mac & Windows).

Moreover sometimes I got black screen and the only way to solve this is to close and restart Streamdeck

Thank you,

**Comment by tubededentifrice** [comment]
Thanks, I indeed have the same problem with the latest version of StreamDeck, something has likely changed (or is broken) in the SDK. I don't have time right now, but I should be able to fix in within ~2 weeks.

**Comment by tubededentifrice** [comment]
Fixed it today, I don't have the problem anymore -- was caused by changes in the SDK I guess (just updating the dependencies fixed it, but took the opportunity to push additional fixes / improvements)

**Comment by tubededentifrice** [comment]
NB: You can update it manually with https://github.com/tubededentifrice/streamdeck-crypto/tree/master/Release
