### ISSUE TITLE
Crypto Ticker Pro on Stream 

### ISSUE THREAD

**Issue by kfenders** [tubededentifrice/streamdeck-crypto#3]
Crypto Ticker Pro for some reason is not picking up some crypto symbols such as Bitcoin Cash (BCH) on Bitfinex.

**Comment by tubededentifrice** [comment]
The plugin uses https://api-pub.bitfinex.com/v2/conf/pub:list:pair:exchange to retrieve the available pairs and BCH doesn't seems to be listed.
It doesn't seems to be listed on their homepage either.
