### ISSUE TITLE
[Feature Request] More assets supported

### ISSUE THREAD

**Issue by DeFiDude** [tubededentifrice/streamdeck-crypto#6]
Not sure what the best route is to get more assets supported (probably writing a PR, though I lack the knowledge), so feel free to just tell me to go away and write it myself.

But in any case, I'd like to signal support for the following assets to be added:

Rocket Pool ($RPL) - A project for staking on Eth 2.0, allowing tokenized deposits, partial staking node rewards, and more.
Perpetual Protocol ($PERP) - On-chain perpetuals
Meme ($MEME) - A platform for NFT art drops, and NFT farming in general (there are two MEME's, the one I'm referring to is only supported on Uniswap so may be hard to pull from an easy to read source)

Thanks!

**Comment by tubededentifrice** [comment]
Hi there
I only want to support Bitfinex API for the moment, newly added pairs will be automatically listed. For a list of pairs, refer to https://www.bitfinex.com/

At some point I may add Binance, but they don't seems to support those coins either.
